// Define the type for the localConfig object
import { SiteConfig } from "./configTypes";

// Export the LocalConfig interface as an alias for backward compatibility
export type LocalConfig = SiteConfig;

const localConfig: LocalConfig = {
  showLogo: true,
  infoBar: {
    backgroundColor: "#801d1e",
    phone: "(912) 356-3258",
    address: "2121 Rowland Ave, Savannah, GA 31404",
    hours: "Mon-Fri: 7:00 AM - 5:00 PM",
    textColor: "#ffffff",
    message: "Professional Auto Service & Repair Since 2008",
  },
  navBar: {
    backgroundColor: "#ffffff",
    textColor: "#801d1e",
    logo: "TC-TITLE.png",
    showLogo: false,
    siteTitle: "Automotion",
    siteTitleGradientFrom: "#801d1e",
    siteTitleGradientTo: "#b27778",
    scheduleButtonText: "Schedule Service",
    scheduleButtonColor: "#801d1e",
    activeTabColor: "#801d1e",
    hamburgerIconColor: "#801d1e",
    hamburgerIconHoverBgColor: "#801d1e20",
    mobileMenuBgColor: "#ffffff",
    mobileNavTextColor: "#111827",
    mobileActiveTabBgColor: "#801d1e20",
    mobileActiveTabTextColor: "#801d1e",
    navLinks: [
      {
        path: "/",
        label: "Home",
      },
      {
        path: "/services",
        label: "Services",
      },
      {
        path: "/reviews",
        label: "Reviews",
      },
      {
        path: "/contact",
        label: "Contact",
      },
    ],
  },
  cursor: {
    enabled: true,
    mobileEnabled: false,
    cursorImage: "blkcursor.png",
    elementCursorImage: "blucursor.png",
  },
  loadingScreen: {
    enabled: true,
    backgroundColor: "rgba(128, 29, 30, 0.21)",
    logoImage: "logo.png",
    logoWidth: 280,
    logoAlt: "Automotion",
    spinner: {
      enabled: true,
      color: "#801d1e",
      size: 60,
      thickness: 4,
    },
    timing: {
      minimumDisplayTime: 300,
      fadeOutDuration: 100,
    },
  },
  browser: {
    title: "Automotion - Professional Auto Repair & Service in Savannah, GA",
    shortTitle: "Automotion",
    faviconFolder: "favicon",
    themeColor: "#801d1e",
  },
  businessInfo: {
    name: "Automotion",
    llcType: "",
    contactEmail: "skaggs@automotionconveyors.com",
    contactPhone: "(912) 356-3258",
    legalPages: {
      privacyPolicy: {
        headerColor: "#801d1e",
        linkColor: "#a66061",
        backgroundColor: "#ffffff",
        textColor: "#1f1f1f",
        borderColor: "#e5e7eb",
        iconColor: "#801d1e",
      },
      termsOfService: {
        headerColor: "#801d1e",
        linkColor: "#a66061",
        backgroundColor: "#ffffff",
        textColor: "#1f1f1f",
        borderColor: "#e5e7eb",
        disclaimerBgColor: "#f9fafb",
        disclaimerTextColor: "#374151",
      },
    },
  },
  pages: {
    Home: {
      badge: "Professional Auto Service & Repair Since 2008",
      heroBadgeColor: "#a6606120",
      heroBadgeTitleColor: "#ffffff",
      title: "Expert Auto Services in ",
      heroTitleColor: "#ffffff",
      location: "Savannah, GA",
      heroLocationColor: "#d8bbbb",
      content: "",
      heroContentColor: "#ffffff",
      subtitle2:
        "Honest, Fair, and Reliable Auto Repair. Professional automotive services, body work, and mechanical repair with exceptional customer service.",
      heroSubtitleColor: "#f2e8e8",
      heroImage: "1.png",
      heroMobileImage: "mobile1.png",
      heroGradientTop: "rgba(128, 29, 30, 1)",
      heroGradientBottom: "#a66061",
      scheduleButtonText: "Get Free Estimate",
      heroScheduleButtonColor: "#801d1e",
      heroScheduleButtonTextColor: "#ffffff",
      heroScheduleButtonHoverColor: "#a66061",
      contactButtonText: "Contact Us",
      heroContactButtonColor: "#00000000",
      heroContactButtonTextColor: "#ffffff",
      heroContactButtonBorderColor: "#ffffff",
      heroContactButtonHoverColor: "rgba(128, 29, 30, 0.41)",
      heroContactButtonHoverTextColor: "#801d1e",
      heroContactButtonHoverBorderColor: "#ffffff",
      heroCard1Text: "Auto Repair",
      heroBox1BgColor: "#a66061",
      heroBox1TextColor: "#ffffff",
      heroBox1BorderColor: "#b27778",
      heroBox1IconBgColor: "#b27778",
      heroBox1IconColor: "#ffffff",
      heroCard2Text: "Body Work",
      heroBox2BgColor: "#a66061",
      heroBox2TextColor: "#ffffff",
      heroBox2BorderColor: "#b27778",
      heroBox2IconBgColor: "#b27778",
      heroBox2IconColor: "#ffffff",
      heroCard3Text: "Mechanical Service",
      heroBox3BgColor: "#a66061",
      heroBox3TextColor: "#ffffff",
      heroBox3BorderColor: "#b27778",
      heroBox3IconBgColor: "#b27778",
      heroBox3IconColor: "#ffffff",
      scheduleSection: {
        scheduleSectionTitle: "BOOK YOUR SERVICE",
        scheduleSectionTitleColor: "#801d1e",
        scheduleSectionBadgeColor: "#a6606136",
        scheduleSectionBadgeTextColor: "#801d1e",
        bookingTitle: "Schedule Your Auto Service",
        bookingTitleColor: "#801d1e",
        scheduleTitlePart1: "Book a time to bring your vehicle to our ",
        scheduleTitlePart1Color: "#111827",
        scheduleTitlePart2: "auto specialists",
        scheduleTitlePart2Color: "#801d1e",
        scheduleIconBgColor: "#b27778",
        scheduleIconColor: "#ffffff",
        scheduleIconImage: "clock.png",
        scheduleAddress: "2121 Rowland Ave, Savannah, GA 31404",
        scheduleAddressColor: "#a66061",
        scheduleContent:
          "Professional auto repair, body work, and mechanical services with honest, fair, and reliable service.",
        scheduleContentColor: "#6b7280",
        calendarRippleStartColor: "#d8bbbb",
        calendarRippleEndColor: "#b27778",
        calendarRippleOpacity: 0.15,
        calendarBgColor: "#ffffff",
        calendarBorderColor: "#d8bbbb",
        calendarAccentColor: "#b27778",
        calendarMonth: "AUGUST",
        calendarYear: "2024",
        calendarEmptyDays: "3",
        calendarDaysInMonth: "31",
        calendarSelectedDay: "15",
        calendarAvailableDays: "5,8,12,15,19,22,26,29",
        calendarTimeSlotsText: "3 Time Slots Available",
        tapToBookText: "Tap to Book",
        tapToBookTextColor: "#000000",
        calendlyUrl: "https://calendly.com/[*ENTER_CALENDLY_URL*]",
        scheduleGradientTop: "#f2e8e8",
        scheduleGradientBottom: "#ffffff",
      },
      guaranteeSection: {
        guaranteeTitle: "Why Choose Us",
        guaranteeBadgeColor: "#f2e8e8c0",
        guaranteeBadgeTextColor: "#801d1e",
        guaranteeIcon1: "access.png",
        guaranteeTitle1: "Honest & Fair",
        guaranteeSubtitle1: "Transparent Pricing",
        guaranteeIconBgColor1: "#ffffff",
        guaranteeIconBorderColor1: "#f2e8e8",
        guaranteeTitleTextColor1: "#111827",
        guaranteeSubtitleTextColor1: "#6b7280",
        guaranteeIcon2: "free.png",
        guaranteeTitle2: "Free Estimates",
        guaranteeSubtitle2: "Quick & Accurate",
        guaranteeIconBgColor2: "#ffffff",
        guaranteeIconBorderColor2: "#f2e8e8",
        guaranteeTitleTextColor2: "#111827",
        guaranteeSubtitleTextColor2: "#6b7280",
        guaranteeCenterLogo: "logo.png",
        guaranteeCenterBgColor: "#ffffff",
        guaranteeCenterBorderColor: "#f2e8e8",
        guaranteeIcon4: "calculator.png",
        guaranteeTitle4: "Insurance Approved",
        guaranteeSubtitle4: "All Major & Minor Companies",
        guaranteeIconBgColor4: "#ffffff",
        guaranteeIconBorderColor4: "#f2e8e8",
        guaranteeTitleTextColor4: "#111827",
        guaranteeSubtitleTextColor4: "#6b7280",
        guaranteeIcon5: "shipping.png",
        guaranteeTitle5: "Towing Service",
        guaranteeSubtitle5: "Towing Service",
        guaranteeIconBgColor5: "#ffffff",
        guaranteeIconBorderColor5: "#f2e8e8",
        guaranteeTitleTextColor5: "#111827",
        guaranteeSubtitleTextColor5: "#6b7280",
        guaranteeIconBgColor: "#ffffff",
        guaranteeIconBorderColor: "#e0e7ff",
        guaranteeTitleTextColor: "#111827",
        guaranteeSubtitleTextColor: "#6b7280",
        guaranteeBgGradientTop: "#f0f9ff",
        guaranteeBgGradientBottom: "#f0f9ff",
        guaranteeDecorativeElements: {
          topCircleFromColor: "#f2e8e8ec",
          topCircleToColor: "#d8bbbb",
          topCircleOpacity: 0.3,
          bottomCircleFromColor: "#f2e8e8ec",
          bottomCircleToColor: "#d8bbbb",
          bottomCircleOpacity: 0.3,
          centerRadialColor: "#ffffff",
          centerRadialOpacity: 0.8,
          item1BgFromColor: "#f2e8e8",
          item1BgViaColor: "#d8bbbb",
          item1BgToColor: "#f2e8e8",
          item2BgFromColor: "#f2e8e8",
          item2BgViaColor: "#d8bbbb",
          item2BgToColor: "#f2e8e8",
          centerBgFromColor: "#f2e8e8",
          centerBgViaColor: "#d8bbbb",
          centerBgToColor: "#f2e8e8",
          item4BgFromColor: "#f2e8e8",
          item4BgViaColor: "#d8bbbb",
          item4BgToColor: "#f2e8e8",
          item5BgFromColor: "#f2e8e8",
          item5BgViaColor: "#d8bbbb",
          item5BgToColor: "#f2e8e8",
          itemHoverFromColor: "#f2e8e8",
          itemHoverToColor: "#d8bbbb",
        },
      },
      servicesSection: {
        servicesBadgeText: "Our Expertise",
        servicesBadgeColor: "#f2e8e8c0",
        servicesBadgeTextColor: "#801d1e",
        servicesTitle: "Professional Auto Services",
        servicesHighlightText: "Auto Services",
        servicesTitleColor: "#111827",
        servicesHighlightColor: "#801d1e",
        servicesHighlightUnderlineColor: "#a6606142",
        servicesDescription:
          "We specialize in tire installation, repair, oil changes, brake service, and general automotive maintenance. Quality work with competitive pricing.",
        servicesDescriptionColor: "#6b7280",
        servicesButtonText: "View All Services",
        servicesButtonUrl: "/services",
        servicesButtonStartColor: "#801d1e",
        servicesButtonEndColor: "#801d1e",
        servicesButtonTextColor: "#ffffff",
        servicesButtonHoverStartColor: "#a66061",
        servicesButtonHoverEndColor: "#a66061",
        serviceReelCardBgColor: "#ffffff",
        serviceReelCardBorderColor: "#f3f4f680",
        serviceReelCardHoverShadowColor: "rgba(0, 0, 0, 0.08)",
        serviceReelIconColor: "#801d1e",
        serviceReelTitleColor: "#111827",
        serviceReelTitleHoverColor: "#801d1e",
        serviceReelDescriptionColor: "#6b7280",
        serviceReelDescriptionHoverColor: "#374151",
        serviceReelMobileIndicatorColor: "#801d1e",
        serviceReelMobileInactiveColor: "#e0e0e0",
        serviceReelGradientFromColor: "#ffffff",
        serviceReelGradientToColor: "#ffffff",
      },
      reviewsSection: {
        reviewsBadgeText: "Verified Google Reviews",
        reviewsBadgeColor: "rgba(255, 255, 255, 0.1)",
        reviewsBadgeTextColor: "#ffffff",
        reviewsTitle: "Reviews from our ",
        reviewsHighlight: "customers",
        reviewsTitleColor: "#ffffff",
        reviewsHighlightColor: "#d8bbbb",
        reviewsSubtitle: "Quality service you can trust",
        reviewsSubtitleColor: "#f2e8e8",
        reviewCardBgColor: "rgba(255, 255, 255, 0.1)",
        reviewCardBorderColor: "rgba(255, 255, 255, 0.2)",
        reviewCardHoverBorderColor: "rgba(255, 255, 255, 0.3)",
        reviewTextColor: "rgba(255, 255, 255, 0.9)",
        reviewAuthorColor: "#ffffff",
        reviewVerifiedColor: "#ffffff",
        reviewStarColor: "#fbbf24",
        viewAllButtonText: "View All Reviews",
        viewAllButtonBgColor: "rgba(255, 255, 255, 0.1)",
        viewAllButtonHoverBgColor: "rgba(255, 255, 255, 0.2)",
        viewAllButtonTextColor: "#ffffff",
        viewAllButtonBorderColor: "rgba(255, 255, 255, 0.2)",
        reviewsBgStartColor: "#b27778",
        reviewsBgMiddleColor: "#a66061",
        reviewsBgEndColor: "#801d1e",
        defaultReviews: [
          {
            text: "This is one of the best tire shops to go to. I've been coming here for Years and the service is always top tier. Mr. Harris always takes care of me and always make sure that I am well taken care of and they have the best tires in town.",
            author: "David Jayy",
            rating: 5,
          },
          {
            text: "The BEST recommendation I've ever gotten! I was told to come into Automotive Repair on wheels today by a friend for my flat tire and was blown away by the amazing customer service and fair prices. Mr. Harris gave excellent customer service and I'll definitely be back for a much needed oil change this week.",
            author: "Linda G",
            rating: 5,
          },
          {
            text: "Mr. Harris is very courteous and friendly. Super helpful. I found myself with a flat on my way to school this morning and he was very quick to respond to my call. Didn't have to wait too long luckily. Prices here were better than quotes I received elsewhere.",
            author: "Ashlee Greene",
            rating: 5,
          },
        ],
      },
    },
    Services: {
      title: "Our Tire & Auto Services",
      heroTitleColor: "#ffffff",
      subtitle:
        "Professional tire installation, repair, and automotive services in Savannah, GA. Quality work at competitive prices.",
      heroSubtitleColor: "#ffffff",
      badge: "Professional Tire & Auto Shop",
      heroBadgeBgColor: "#801d1e3a",
      heroBadgeTextColor: "#ffffff",
      heroBadgeIconColor: "#d8bbbb",
      heroBadgeCheckmarkColor: "#ffcfcf",
      heroBadgeMedalIconColor: "#ffcfcf",
      card1Title: "Years Experience",
      card1Value: "20+",
      card2Title: "Vehicles Serviced",
      card2Value: "10000+",
      heroStatsCardBgColor: "#801d1e4f",
      heroStatsCardTextColor: "#ffffff",
      heroStatsCardValueColor: "#ffffff",
      heroStatsCardIconColor: "#d8bbbb",
      heroImage: "/images/auto-services-hero.jpg",
      heroBgGradientFrom: "#801d1e",
      heroBgGradientVia: "#a66061",
      heroBgGradientTo: "#b27778",
      heroBlurredCircle1Color: "#a66061",
      heroBlurredCircle2Color: "#b27778",
      heroPatternColor: "#ffffff",
      heroLightBeam1Color: "#a66061",
      heroLightBeam2Color: "#d8bbbb",
      serviceCategoriesBgColor: "#ffffff",
      serviceCategoriesGradientOpacity: 0.7,
      serviceCategoriesBgColorFrom: "#ffffff",
      serviceCategoriesBgColorTo: "#ffffff",
      serviceCategoryCardTitleColor: "#ffffff",
      serviceCategoryCardDescriptionColor: "#801d1e",
      serviceCategoryCardBorderColor: "#e5e7eb",
      serviceCategoryCardButtonColor: "#ffffff",
      serviceCategoryCardButtonBgColor: "rgba(255, 255, 255, 0.1)",
      serviceCategoryCardButtonHoverBgColor: "#801d1e",
      serviceCategoryCardButtonHoverColor: "#ffffff",
      serviceCategories: [
        {
          id: "tires",
          title: "Tire Services",
          titleColor: "#ffffff",
          description:
            "New and used tire installation, repair, and maintenance services for all vehicle types",
          descriptionColor: "#ffffff",
          bgImage: "2.png",
          color: "#801d1e-#a66061",
          iconColor: "#ffffff",
          borderColor: "#801d1e",
          icon: "WrenchScrewdriverIcon",
          services: [
            {
              title: "New Tire Installation",
              description:
                "Professional installation of new tires with proper balancing and alignment to ensure optimal performance and safety.",
              icon: "WrenchScrewdriverIcon",
              iconColor: "#a66061",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Used Tire Sales",
              description:
                "Quality used tires at competitive prices. All tires inspected for safety and performance before sale.",
              icon: "CogIcon",
              iconColor: "#a66061",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Tire Repair & Patching",
              description:
                "Expert tire repair services including patching, plugging, and sidewall repairs to extend tire life.",
              icon: "PaintBrushIcon",
              iconColor: "#a66061",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Tire Balancing",
              description:
                "Professional wheel balancing services to eliminate vibration and ensure smooth driving experience.",
              icon: "WrenchIcon",
              iconColor: "#a66061",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
          ],
        },
        {
          id: "automotive",
          title: "Automotive Services",
          titleColor: "#ffffff",
          description:
            "Complete automotive maintenance and repair services to keep your vehicle running smoothly",
          descriptionColor: "#ffffff",
          bgImage: "3.png",
          color: "#801d1e-#a66061",
          iconColor: "#ffffff",
          borderColor: "#801d1e",
          icon: "SparklesIcon",
          services: [
            {
              title: "Oil Changes",
              description:
                "Quick and professional oil change services using quality motor oil to keep your engine running smoothly and efficiently.",
              icon: "SparklesIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Brake Service",
              description:
                "Complete brake system inspection, repair, and replacement services including brake pads, rotors, and brake fluid changes.",
              icon: "ShieldCheckIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "General Repairs",
              description:
                "Comprehensive automotive repair services for engine issues, electrical problems, and general maintenance needs.",
              icon: "WrenchScrewdriverIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Vehicle Diagnostics",
              description:
                "Professional diagnostic services to identify and troubleshoot automotive problems quickly and accurately.",
              icon: "CogIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
          ],
        },
        {
          id: "emergency",
          title: "Emergency Services",
          titleColor: "#ffffff",
          description:
            "24/7 emergency tire and roadside assistance services when you need help most",
          bgImage: "4.png",
          color: "#801d1e-#a66061",
          iconColor: "#ffffff",
          borderColor: "#801d1e",
          descriptionColor: "#ffffff",
          icon: "CogIcon",
          services: [
            {
              title: "Flat Tire Repair",
              description:
                "Emergency flat tire repair and replacement services to get you back on the road quickly and safely.",
              icon: "BeakerIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Mobile Tire Service",
              description:
                "On-site tire installation and repair services. We come to you for convenient roadside assistance.",
              icon: "ExclamationTriangleIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Emergency Repairs",
              description:
                "Quick emergency automotive repairs to get you safely back on the road",
              icon: "TruckIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
            {
              title: "Roadside Assistance",
              description:
                "Comprehensive roadside assistance including jump starts, lockout service, and emergency towing coordination.",
              icon: "WrenchIcon",
              iconColor: "#801d1e",
              titleColor: "#111827",
              descriptionColor: "#6b7280",
              bgColor: "#f9fafb",
              borderColor: "#e5e7eb",
            },
          ],
        },
      ],
      ctaBgGradientFrom: "#801d1e",
      ctaBgGradientVia: "#a66061",
      ctaBgGradientTo: "#b27778",
      ctaBgPatternColor: "#ffffff60",
      ctaCardBgColor: "#ffffff2f",
      ctaCardBorderColor: "#ffffff20",
      scheduleButtonText: "Schedule Estimate",
      scheduleButtonBgColor: "#ffffff",
      scheduleButtonTextColor: "#801d1e",
      scheduleButtonHoverBgColor: "#f3f4f6",
      callButtonText: "Call Us Now",
      callButtonBgColor: "#801d1e",
      callButtonTextColor: "#ffffff",
      callButtonHoverBgColor: "#a66061",
      ctaTitle: "Need Quality Tire Service?",
      ctaTitleColor: "#ffffff",
      ctaDescription:
        "Contact us today for professional tire installation, repair, and automotive services at competitive prices.",
      ctaDescriptionColor: "#ffffff",
    },
    Reviews: {
      title: "Customer Reviews",
      heroTitleColor: "#ffffff",
      subtitle:
        "We're proud of the work we do and the trust our customers place in us. Here's what they have to say about their collision repair experience.",
      heroSubtitleColor: "#ffffff",
      badge: "Verified Google Reviews",
      heroBadgeBgColor: "#ffffff10",
      heroBadgeTextColor: "#ffffff",
      heroBadgeIconColor: "#f2e8e8",
      heroBadgeCheckmarkColor: "#f2e8e8",
      heroBadgeBorderColor: "#a66061",
      statsCard1Title: "Verified Reviews",
      statsCard1IconColor: "#f2e8e8",
      statsCard1BlurGradientFrom: "#801d1e",
      statsCard1BlurGradientTo: "#a66061",
      statsCard2Title: "Average Rating",
      statsCard2IconColor: "#facc15",
      statsCard2BlurGradientFrom: "#a66061",
      statsCard2BlurGradientTo: "#801d1e",
      statsCardBgColor: "#ffffff10",
      statsCardTextColor: "#f3f4f6",
      statsCardTitleColor: "#ffffff",
      statsCardBorderColor: "#ffffff20",
      statsCardHoverBorderColor: "#ffffff30",
      heroImage: "/images/auto-reviews-hero.jpg",
      heroBgGradientFrom: "#801d1e",
      heroBgGradientVia: "#a66061",
      heroBgGradientTo: "#b27778",
      heroBlurredCircle1Color: "#a66061",
      heroBlurredCircle2Color: "#d8bbbb",
      heroBlurredCircle3Color: "#f2e8e8",
      heroLightBeam1Color: "#a66061",
      heroLightBeam2Color: "#d8bbbb",
      heroPatternColor: "#ffffff",
      heroPatternOpacity: 0.1,
      reviewsSectionBgColor: "#f2e8e82a",
      reviewCardBgColor: "#ffffff",
      reviewCardHoverShadow: "lg",
      reviewCardBorderColor: "#e5e7eb",
      reviewCardTextColor: "#4b5563",
      reviewCardAuthorNameColor: "#111827",
      reviewCardSourceColor: "#6b7280",
      reviewCardStarColor: "#facc15",
      reviewCardStarEmptyColor: "#d1d5db",
      reviewCardShowMoreColor: "#801d1e",
      reviewCardShowMoreHoverColor: "#a66061",
      reviewCardGradientColor: "#801d1e",
      reviewAvatarColors: [
        "#801d1e",
        "#a66061",
        "#b27778",
        "#d8bbbb",
        "#f2e8e8",
        "#801d1e",
        "#a66061",
        "#b27778",
      ],
      reviewAvatarTextColor: "#ffffff",
      paginationButtonBgColor: "#801d1e",
      paginationButtonTextColor: "#ffffff",
      paginationButtonDisabledOpacity: 0.5,
      paginationTextColor: "#4b5563",
      shareExperienceBgColor: "#ffffff",
      shareExperienceBorderColor: "#e5e7eb",
      shareExperienceShadow: "sm",
      shareExperienceHoverShadow: "md",
      shareExperienceTitleColor: "#111827",
      shareExperienceSubtitleColor: "#4b5563",
      shareExperienceGradientColor: "#801d1e",
      shareExperienceGradientOpacity: 0.5,
      shareButtonBgColor: "#801d1e",
      shareButtonTextColor: "#ffffff",
      shareButtonHoverBgColor: "#a66061",
      shareButtonShadow: "sm",
      shareButtonHoverShadow: "md",
      shareButtonText: "Write a Review on Google",
      shareButtonLink: "https://g.co/kgs/Sh3fpBf",
      shareExperienceTitle: "Share Your Experience",
      shareExperienceSubtitle: "Help others by sharing your experience with us",
      ctaBgGradientFrom: "#801d1e",
      ctaBgGradientVia: "#a66061",
      ctaBgGradientTo: "#b27778",
      ctaPatternColor: "#ffffff",
      ctaPatternOpacity: 0.05,
      ctaCardBgColor: "#ffffff0d",
      ctaCardBlurAmount: "2px",
      ctaScheduleButtonText: "Schedule Now",
      ctaScheduleButtonBgColor: "#ffffff",
      ctaScheduleButtonTextColor: "#801d1e",
      ctaScheduleButtonHoverBgColor: "#f3f4f6",
      ctaCallButtonText: "Call Us Now",
      ctaCallButtonBgColor: "#801d1e",
      ctaCallButtonTextColor: "#ffffff",
      ctaCallButtonHoverBgColor: "#a66061",
      ctaTitle: "Ready to Get Your Car Back to Perfect?",
      ctaTitleColor: "#ffffff",
      ctaDescription:
        "Schedule your appointment today and experience the difference expert auto body repair makes.",
      ctaDescriptionColor: "#f2e8e8",
    },
    Careers: {
      heroPaddingTop: "150px",
      heroBgGradientFrom: "#801d1e",
      heroBgGradientVia: "#a66061",
      heroBgGradientTo: "#b27778",
      heroBlurredCircle1Color: "#a66061",
      heroBlurredCircle1Opacity: 0.2,
      heroBlurredCircle2Color: "#b27778",
      heroBlurredCircle2Opacity: 0.2,
      heroPatternColor: "#ffffff",
      heroPatternOpacity: 0.3,
      waveSeparatorColor: "#801d1e81",
      waveSeparatorHeight: "250px",
      applicationSectionBgColor: "#ffffff",
      applicationFormShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.35)",
      hireBadgeText: "We're hiring passionate professionals",
      hireBadgeBgColor: "#ffffff10",
      hireBadgeBorderColor: "#ffffff20",
      hireBadgeTextColor: "#ffffff",
      hireTitle: "Join Our Team",
      hireTitleColor: "#ffffff",
      hireTitleHighlightColor: "#ffffff",
      hireTitleGlowColor: "#ffffff",
      hireTitleGlowOpacity: 0.3,
      hireSubtitle:
        "Build your career with Taylor's Collision. We're looking for talented individuals who are passionate about auto body repair and customer service.",
      hireSubtitleColor: "#ffffff",
      hireSubtitleOpacity: 0.9,
      formHeaderBgFrom: "#a66061",
      formHeaderBgTo: "#801d1e",
      formHeaderPatternColor: "#ffffff",
      formHeaderPatternOpacity: 0.15,
      formHeaderPatternSize: "16px",
      formHeaderTitleText: "Application Form",
      formHeaderTitleColor: "#ffffff",
      formHeaderSubtitleText:
        "Fill out the form below to apply for a position with our team",
      formHeaderSubtitleColor: "#ffffff",
      formHeaderSubtitleOpacity: 0.8,
      formSectionBgColor: "#f9fafb",
      formSectionBorderColor: "#e5e7eb",
      formSectionTitleColor: "#801d1e",
      formSectionHoverShadow: "md",
      formInputBgColor: "#ffffff",
      formInputBorderColor: "#d1d5db",
      formInputTextColor: "#111827",
      formInputFocusRingColor: "#a66061",
      formInputFocusBorderColor: "#801d1e",
      formInputBorderRadius: "xl",
      formInputPadding: "px-4 py-3",
      formLabelColor: "#374151",
      formErrorColor: "#ef4444",
      positionOptions: [
        "Auto Body Technician",
        "Collision Repair Specialist",
        "Paint Technician",
        "Frame Repair Technician",
        "Customer Service",
        "Other",
      ],
      addReferenceBtnBgColor: "#801d1e",
      addReferenceBtnHoverBgColor: "#a66061",
      addReferenceBtnTextColor: "#ffffff",
      removeReferenceBtnColor: "#ef4444",
      removeReferenceBtnHoverColor: "#dc2626",
      submitButtonBgFrom: "#801d1e",
      submitButtonBgTo: "#a66061",
      submitButtonTextColor: "#ffffff",
      submitButtonHoverShadow: "xl",
      submitButtonBorderRadius: "xl",
      successMessageBgColor: "#f2e8e8",
      successMessageBorderColor: "#f2e8e8",
      successMessageTextColor: "#801d1e",
      errorMessageBgColor: "#fef2f2",
      errorMessageBorderColor: "#fecaca",
      errorMessageTextColor: "#991b1b",
      mobileOverlay: {
        enabled: true,
        mobileBreakpoint: 663,
        title: "Desktop View Required",
        message:
          "Our job application form requires a larger screen. Please visit this page on a desktop or laptop computer for the best experience.",
        buttonText: "Back to Home Page",
        buttonLink: "/",
        footerText:
          "If you're already on a desktop device, please increase your browser window size.",
        backgroundOpacity: 0.9,
        overlayZIndex: 50,
        cardBackgroundColor: "#ffffff",
        cardBorderRadius: "2xl",
        cardBorderTopWidth: 4,
        cardBoxShadow: "2xl",
        iconBackgroundOpacity: 0.3,
        iconWidth: 20,
        iconHeight: 20,
        titleFontSize: "2xl",
        titleFontWeight: "bold",
        messageColor: "#4b5563",
        buttonWidth: "full",
        buttonPadding: "py-3 px-4",
        buttonTextColor: "#ffffff",
        buttonFontWeight: "medium",
        buttonBorderRadius: "lg",
        buttonShadow: "md",
        buttonHoverScale: 1.05,
        buttonTapScale: 0.95,
        footerMarginTop: 6,
        footerPaddingTop: 6,
        footerBorderColor: "#e5e7eb",
        footerTextColor: "#6b7280",
        footerTextSize: "sm",
      },
    },
    Contact: {
      title: "Get in Touch",
      heroTitleColor: "#ffffff",
      heroTitleGradientFrom: "#ffffff",
      heroTitleGradientVia: "#ffffff",
      heroTitleGradientTo: "#ffffff",
      heroTitleGlowColor: "#f2e8e8",
      heroTitleGlowOpacity: 0.3,
      subtitle:
        "Need tire service or automotive repair? Have questions about our services? We're here to help.",
      heroSubtitleColor: "#ffffff",
      heroSubtitleHighlightBgColor: "#801d1e",
      badge: "Quality Service Guaranteed",
      heroBadgeBgColor: "#ffffff1a",
      heroBadgeTextColor: "#ffffff",
      heroBadgeIconColor: "#d8bbbb",
      heroBadgeBorderColor: "#ffffff33",
      featureBadge1Text: "Experienced Team",
      featureBadge1IconColor: "#d8bbbb",
      featureBadge1BgColor: "#ffffff1a",
      featureBadge1BorderColor: "#ffffff33",
      featureBadge1TextColor: "#ffffff",
      featureBadge2Text: "Competitive Pricing",
      featureBadge2IconColor: "#d8bbbb",
      featureBadge2BgColor: "#ffffff1a",
      featureBadge2BorderColor: "#ffffff33",
      featureBadge2TextColor: "#ffffff",
      heroImage: "/images/auto-contact-hero.jpg",
      heroBgGradientFrom: "#801d1e",
      heroBgGradientVia: "#a66061",
      heroBgGradientTo: "#b27778",
      heroBlurredCircle1Color: "#a66061",
      heroBlurredCircle1Opacity: 0.2,
      heroBlurredCircle2Color: "#b27778",
      heroBlurredCircle2Opacity: 0.2,
      heroPatternColor: "#ffffff",
      heroPatternOpacity: 0.3,
      heroLightBeam1Color: "#a66061",
      heroLightBeam1Opacity: 0.2,
      heroLightBeam2Color: "#b27778",
      heroLightBeam2Opacity: 0.2,
      contactSectionBgColor: "#f2e8e81f",
      contactInfoTitleText: "Contact Information",
      contactInfoTitleColor: "#801d1e",
      contactIconBgColor: "#f2e8e842",
      contactIconColor: "#801d1e",
      contactLabelColor: "#111827",
      contactTextColor: "#4b5563",
      contactLinkHoverColor: "#a66061",
      phoneIcon: "PhoneIcon",
      phoneLabel: "Phone",
      phoneNumber: "(912) 356-3258",
      phoneNumberLink: "tel:+19123563258",
      emailIcon: "EnvelopeIcon",
      emailLabel: "Email",
      emailAddress: "skaggs@automotionconveyors.com",
      emailAddressLink: "mailto:skaggs@automotionconveyors.com",
      locationIcon: "MapPinIcon",
      locationLabel: "Location",
      locationAddress: "2121 Rowland Ave,\nSavannah, GA 31404",
      hoursIcon: "ClockIcon",
      hoursLabel: "Business Hours",
      hoursText: "Monday - Friday: 7:00 AM - 5:00 PM\nSaturday: Closed",
      googleMapEmbedUrl:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3448.8234756!2d-81.0937378!3d32.0735649!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88fb75fc78c1e8c5%3A0x1234567890abcdef!2s2121%20Rowland%20Ave%2C%20Savannah%2C%20GA%2031404!5e0!3m2!1sen!2sus!4v1640995200000!5m2!1sen!2sus",
      googleMapHeight: "300px",
      googleMapBorderRadius: "lg",
      googleMapShadow: "lg",
      formTitleText: "Send Us a Message",
      formTitleColor: "#111827",
      formLabelColor: "#374151",
      formInputBgColor: "#ffffff",
      formInputBorderColor: "#d1d5db",
      formInputTextColor: "#111827",
      formInputFocusRingColor: "#801d1e",
      formInputBorderRadius: "lg",
      formInputPadding: "px-4 py-3",
      formFieldFullName: "Full Name",
      formFieldEmail: "Email Address",
      formFieldPhone: "Phone Number",
      formFieldService: "Service Needed",
      formFieldMessage: "Message",
      serviceOptions: [
        "General Inquiry",
        "Collision Repair",
        "Auto Body Work",
        "Paint Services",
        "Insurance Claims",
        "Frame Repair",
        "Free Estimate",
      ],
      formSubmitBtnText: "Send Message",
      formSubmitBtnBgColor: "#801d1e",
      formSubmitBtnTextColor: "#ffffff",
      formSubmitBtnHoverBgColor: "#a66061",
      formSubmitBtnBorderRadius: "lg",
      ctaBgGradientFrom: "#801d1e",
      ctaBgGradientVia: "#a66061",
      ctaBgGradientTo: "#b27778",
      ctaPatternColor: "#ffffff",
      ctaPatternOpacity: 0.05,
      ctaCardBgColor: "#ffffff0d",
      ctaCardBlurAmount: "2px",
      ctaScheduleButtonText: "Schedule Now",
      ctaScheduleButtonBgColor: "#ffffff",
      ctaScheduleButtonTextColor: "#801d1e",
      ctaScheduleButtonHoverBgColor: "#f3f4f6",
      ctaCallButtonText: "Call Us Now",
      ctaCallButtonBgColor: "#801d1e",
      ctaCallButtonTextColor: "#ffffff",
      ctaCallButtonHoverBgColor: "#a66061",
      ctaTitle: "Ready to Get Your Car Back to Perfect?",
      ctaTitleColor: "#ffffff",
      ctaDescription:
        "Schedule your appointment today and experience the difference expert auto body repair makes.",
      ctaDescriptionColor: "#f2e8e8",
    },
  },
  theme: {
    primary600: "#a66061",
    primary700: "#801d1e",
  },
  navLinks: [
    {
      path: "/",
      label: "Home",
    },
    {
      path: "/services",
      label: "Services",
    },
    {
      path: "/reviews",
      label: "Reviews",
    },
    {
      path: "/contact",
      label: "Contact",
    },
  ],
  policies: {
    terms: "Our terms of service text here.",
    privacy: "Our privacy policy text here.",
  },
  description:
    "Professional tire shop in Savannah, GA - Quality tire installation & automotive repair",
  contactInfo: {
    address: "2121 Rowland Ave, Savannah, GA 31404",
    phone: "(912) 356-3258",
    email: "skaggs@automotionconveyors.com",
  },
  hours: {
    weekday: "Monday - Friday: 7:00 AM - 5:00 PM",
    weekend: "Saturday: Closed",
  },
  footerLinks: [
    {
      path: "/",
      label: "Home",
    },
    {
      path: "/services",
      label: "Services",
    },
    {
      path: "/reviews",
      label: "Reviews",
    },
    {
      path: "/contact",
      label: "Contact",
    },
  ],
  socialLinks: {
    twitter: "https://twitter.com/company",
    facebook: "https://facebook.com/company",
    linkedin: "https://linkedin.com/company/company",
    instagram: "https://instagram.com/company",
  },
  showJoinTeamButton: true,
  joinTeamText: "Join the Team",
  joinTeamLink: "/careers",
  copyright: "© 2025 Automotion. All rights reserved.",
  footerStyle: {
    backgroundColor: "#ffffff",
    gradientFromColor: "#f2e8e8",
    gradientToColor: "#ffffff",
    titleColor: "#801d1e",
    textColor: "#111827",
    linkColor: "#801d1e",
    linkHoverColor: "#a66061",
    socialIconColor: "#801d1e",
    dividerColor: "rgba(30, 58, 138, 0.2)",
    quickLinksTitleColor: "#801d1e",
    contactInfoTitleColor: "#801d1e",
    infoTitleColor: "#801d1e",
    joinButtonBgColor: "#801d1e",
    joinButtonTextColor: "#ffffff",
    joinButtonHoverBgColor: "#a66061",
    hoursCardBgColor: "rgba(30, 58, 138, 0.04)",
    hoursCardTextColor: "#111827",
    hoursCardValueColor: "#801d1e",
    copyrightTextColor: "#6b7280",
    policyLinkColor: "#801d1e",
    policyLinkHoverColor: "#a66061",
  },
  schedulingButtonText: "Get Quote",
  themeColor: "#801d1e",
  themeLink: "",
  companyName: "Automotion",
};

export default localConfig;
